#!/bin/bash

# Applies a cmd to each line of the inputs.
#   The input can come from either a file or stdin via a pipe.
#   This is very similar to running:
       # cat $SOMEFILE | xargs -I line my_cmd line

# Determine the file to read from.
# Either the first argument or stdin if from a pipe
ftype=$(stat -f "%T" $stdin)
if [[ "$ftype" != "|" ]]; then
   if [[ "$#" -lt 1 ]]; then
     echo "map FILE [CMD] [ARGS...]"
     exit 1
   fi

   FILE=$1
   CMD="${@:2}"
else
   FILE=${FILE:-/dev/stdin}
   CMD=$@
fi

# CMD defaults to echo if no args are passed
CMD=${CMD:-echo}

# Run command on each line of input.
while read -r line; do
   $CMD $line
done < $FILE
