#!/bin/bash

# Removes extra whitespace

# Determine the file to read from.
# Either the first argument or stdin if from a pipe
ftype=$(stat -f "%T" $stdin)
if [[ "$ftype" != "|" ]]; then
   if [[ "$#" -lt 1 ]]; then
     echo "map FILE [CMD] [ARGS...]"
     exit 1
   fi

   FILE=$1
else
   FILE=${FILE:-/dev/stdin}
fi

# Remove convert tabs to spaces, remove extra spaces and trim whitespace from beginning and end.
cat $FILE | tr -s '\t' ' ' | sed -e 's/^[[:space:]]*//' | sed -e 's/[[:space:]]*$//'
