#!/bin/bash

# Removes extra whitespace

# Determine the file to read from.
# Either the first argument or stdin if from a pipe
ftype=$(stat -f "%T" $stdin)
if [[ "$ftype" != "|" ]]; then
   if [[ "$#" -lt 1 ]]; then
     echo "map FILE [CMD] [ARGS...]"
     exit 1
   fi

   FILE=$1
else
   FILE=${FILE:-/dev/stdin}
fi

# Remove extra spaces
cat $FILE | tr -s ' ' | sed -e 's/^[[:space:]]*//' | sed -e 's/[[:space:]]*$//'
