#!/bin/bash

# Unescapes strings
#   ie: {\"key\": \"value\"} ->
#       { "key":   "value"} ->
#
#   The input can come from either a file or stdin via a pipe.

# Determine the file to read from.
# Either the first argument or stdin if from a pipe
ftype=$(stat -f "%T" $stdin)

if [[ "$ftype" != "|" ]]; then
   if [[ "$#" -lt 1 ]]; then
     echo "unescape_str FILE"
     exit 1
   fi

   FILE=$1
else
   FILE=${FILE:-/dev/stdin}
fi

# print just the match
NEWLINES='s/\\\\n/\\n/g'
QUOTES='s/\\"/"/g'

sed -e $NEWLINES -e $QUOTES $FILE
