#!/bin/bash

# Unwrap strings
#   ie: "onetwothree" -> onetwothree
#
#   The input can come from either a file or stdin via a pipe.

# Determine the file to read from.
# Either the first argument or stdin if from a pipe
ftype=$(stat -f "%T" $stdin)

if [[ "$ftype" != "|" ]]; then
   if [[ "$#" -lt 1 ]]; then
     echo "unwrap_str FILE"
     exit 1
   fi

   FILE=$1
else
   FILE=${FILE:-/dev/stdin}
fi

# remove first and last characters
sed 's/^.\(.*\).$/\1/' $FILE
